#!/usr/bin/env bash
# installs nginx and configures it on a remote server

sudo apt-get update -y

sudo apt-get install nginx -y

echo 'Hello World!' > /var/www/html/index.html

sudo service nginx restart